services:
  server:
    build:
      context: .
    ports:
      - '9000:80'
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./app:/var/www/html
    networks:
      - app-network

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
    platform: linux/amd64
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
